// <auto-generated />
using System;
using CoffeeHouse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeHouse.Migrations
{
    [DbContext(typeof(CoffeeHouseContext))]
    [Migration("20250519161815_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeHouse.Models.TbChiTietHoaDonBan", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .HasColumnType("uuid");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LineTotal")
                        .HasPrecision(21, 2)
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MaHoaDon", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("TbChiTietHoaDonBans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.CartItem", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbHoaDonBan", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaQuan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaQuan");

                    b.ToTable("TbHoaDonBans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbKhachHang", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumberkhachHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("CustomerId");

                    b.HasIndex("PhoneNumberkhachHang")
                        .HasDatabaseName("IX_TbKhachHang_PhoneNumberkhachHang");

                    b.ToTable("TbKhachHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNguyenLieu", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("QuantityToiThieu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IngredientId");

                    b.ToTable("TbNguyenLieus");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhaCungCap", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Stk")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SupplierId");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_TbNhaCungCap_PhoneNumber");

                    b.ToTable("TbNhaCungCaps");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SalaryCoefficient")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MaQuan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_TbNhanVien_Email");

                    b.HasIndex("MaQuan");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_TbNhanVien_PhoneNumber");

                    b.HasIndex("IdentityCardNumber")
                        .HasDatabaseName("IX_TbNhanVien_IdentityCardNumber");

                    b.ToTable("TbNhanViens");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhomSanPham", b =>
                {
                    b.Property<int>("MaNhomSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhomSp"));

                    b.Property<string>("TenNhomSp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaNhomSp");

                    b.ToTable("TbNhomSanPhams");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapChiTiet", b =>
                {
                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("LineTotal")
                        .HasPrecision(21, 4)
                        .HasColumnType("decimal(20, 4)");

                    b.HasKey("PurchaseOrderId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapHang", b =>
                {
                    b.Property<Guid>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaQuan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaQuan");

                    b.ToTable("TbPhieuNhapHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuanCafe", b =>
                {
                    b.Property<int>("MaQuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaQuan"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenQuan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaQuan");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_TbQuanCafe_Email");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_TbQuanCafe_PhoneNumber");

                    b.ToTable("TbQuanCafes");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuanTriVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuyen", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("RoleId");

                    b.HasIndex("TenQuyen")
                        .HasDatabaseName("IX_TbQuyen_TenQuyen");

                    b.ToTable("TbQuyens");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbSanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("MaNhomSp")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaNhomSp");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_TbSanPham_ProductName");

                    b.ToTable("TbSanPhams");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenTaiKhoan")
                        .HasDatabaseName("IX_TbTaiKhoan_TenTaiKhoan");

                    b.ToTable("TbTaiKhoans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTaiKhoanKh", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenTaiKhoan")
                        .HasDatabaseName("IX_TbTaiKhoanKh_TenTaiKhoan");

                    b.ToTable("TbTaiKhoanKhs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTinTuc", b =>
                {
                    b.Property<int>("NewsArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NewsArticleId"));

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("NewsArticleId");

                    b.ToTable("TbTinTucs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbChiTietHoaDonBan", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbHoaDonBan", "MaHoaDonNavigation")
                        .WithMany("TbChiTietHoaDonBans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbSanPham", "MaSanPhamNavigation")
                        .WithMany("TbChiTietHoaDonBans")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.CartItem", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbKhachHang", "CustomerIdNavigation")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbSanPham", "MaSanPhamNavigation")
                        .WithMany("CartItems")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerIdNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbHoaDonBan", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbKhachHang", "CustomerIdNavigation")
                        .WithMany("TbHoaDonBans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbNhanVien", "MaNhanVienNavigation")
                        .WithMany("TbHoaDonBans")
                        .HasForeignKey("MaNhanVien");

                    b.HasOne("CoffeeHouse.Models.TbQuanCafe", "MaQuanNavigation")
                        .WithMany("TbHoaDonBans")
                        .HasForeignKey("MaQuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerIdNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaQuanNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhanVien", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbQuanCafe", "MaQuanNavigation")
                        .WithMany("TbNhanViens")
                        .HasForeignKey("MaQuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaQuanNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapChiTiet", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbNguyenLieu", "IngredientIdNavigation")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbPhieuNhapHang", "PurchaseOrderIdNavigation")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientIdNavigation");

                    b.Navigation("PurchaseOrderIdNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapHang", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbNhaCungCap", "SupplierIdNavigation")
                        .WithMany("TbPhieuNhapHangs")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbNhanVien", "MaNhanVienNavigation")
                        .WithMany("TbPhieuNhapHangs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbQuanCafe", "MaQuanNavigation")
                        .WithMany("TbPhieuNhapHangs")
                        .HasForeignKey("MaQuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplierIdNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaQuanNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbSanPham", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbNhomSanPham", "MaNhomSpNavigation")
                        .WithMany("TbSanPhams")
                        .HasForeignKey("MaNhomSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNhomSpNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTaiKhoan", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbNhanVien", "MaNhanVienNavigation")
                        .WithMany("TbTaiKhoans")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbQuyen", "RoleIdNavigation")
                        .WithMany("TbTaiKhoans")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("RoleIdNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTaiKhoanKh", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbKhachHang", "CustomerIdNavigation")
                        .WithMany("TbTaiKhoanKhs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbQuyen", "RoleIdNavigation")
                        .WithMany("TbTaiKhoanKhs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerIdNavigation");

                    b.Navigation("RoleIdNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbHoaDonBan", b =>
                {
                    b.Navigation("TbChiTietHoaDonBans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbKhachHang", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("TbHoaDonBans");

                    b.Navigation("TbTaiKhoanKhs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNguyenLieu", b =>
                {
                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhaCungCap", b =>
                {
                    b.Navigation("TbPhieuNhapHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhanVien", b =>
                {
                    b.Navigation("TbHoaDonBans");

                    b.Navigation("TbPhieuNhapHangs");

                    b.Navigation("TbTaiKhoans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhomSanPham", b =>
                {
                    b.Navigation("TbSanPhams");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapHang", b =>
                {
                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuanCafe", b =>
                {
                    b.Navigation("TbHoaDonBans");

                    b.Navigation("TbNhanViens");

                    b.Navigation("TbPhieuNhapHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuyen", b =>
                {
                    b.Navigation("TbTaiKhoanKhs");

                    b.Navigation("TbTaiKhoans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbSanPham", b =>
                {
                    b.Navigation("TbChiTietHoaDonBans");

                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}

