// <auto-generated />
using System;
using CoffeeHouse;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeHouse.Migrations
{
    [DbContext(typeof(CoffeeHouseContext))]
    [Migration("20250519161815_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeHouse.Models.TbChiTietHoaDonBan", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .HasColumnType("uuid");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("integer");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ThanhTien")
                        .HasPrecision(21, 2)
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MaHoaDon", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("TbChiTietHoaDonBans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbGioHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("MaKhachHang", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("TbGioHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbHoaDonBan", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaQuan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaQuan");

                    b.ToTable("TbHoaDonBans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbKhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SdtkhachHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("SdtkhachHang")
                        .HasDatabaseName("IX_TbKhachHang_SdtkhachHang");

                    b.ToTable("TbKhachHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNguyenLieu", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SoLuongToiThieu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaNguyenLieu");

                    b.ToTable("TbNguyenLieus");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sdtncc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Stk")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaNhaCungCap");

                    b.HasIndex("Sdtncc")
                        .HasDatabaseName("IX_TbNhaCungCap_Sdtncc");

                    b.ToTable("TbNhaCungCaps");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("boolean");

                    b.Property<decimal>("HeSoLuong")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MaQuan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SoCccd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_TbNhanVien_Email");

                    b.HasIndex("MaQuan");

                    b.HasIndex("Sdt")
                        .HasDatabaseName("IX_TbNhanVien_Sdt");

                    b.HasIndex("SoCccd")
                        .HasDatabaseName("IX_TbNhanVien_SoCccd");

                    b.ToTable("TbNhanViens");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhomSanPham", b =>
                {
                    b.Property<int>("MaNhomSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhomSp"));

                    b.Property<string>("TenNhomSp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaNhomSp");

                    b.ToTable("TbNhomSanPhams");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapChiTiet", b =>
                {
                    b.Property<Guid>("MaPhieuNhap")
                        .HasColumnType("uuid");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("integer");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("ThanhTien")
                        .HasPrecision(21, 4)
                        .HasColumnType("decimal(20, 4)");

                    b.HasKey("MaPhieuNhap", "MaNguyenLieu");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("TbPhieuNhapChiTiets");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapHang", b =>
                {
                    b.Property<Guid>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("integer");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaQuan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaQuan");

                    b.ToTable("TbPhieuNhapHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuanCafe", b =>
                {
                    b.Property<int>("MaQuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaQuan"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenQuan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaQuan");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_TbQuanCafe_Email");

                    b.HasIndex("Sdt")
                        .HasDatabaseName("IX_TbQuanCafe_Sdt");

                    b.ToTable("TbQuanCafes");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuanTriVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("TbQuanTriViens");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaQuyen");

                    b.HasIndex("TenQuyen")
                        .HasDatabaseName("IX_TbQuyen_TenQuyen");

                    b.ToTable("TbQuyens");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbSanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<int>("MaNhomSp")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaNhomSp");

                    b.HasIndex("TenSanPham")
                        .HasDatabaseName("IX_TbSanPham_TenSanPham");

                    b.ToTable("TbSanPhams");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaQuyen");

                    b.HasIndex("TenTaiKhoan")
                        .HasDatabaseName("IX_TbTaiKhoan_TenTaiKhoan");

                    b.ToTable("TbTaiKhoans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTaiKhoanKh", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaQuyen");

                    b.HasIndex("TenTaiKhoan")
                        .HasDatabaseName("IX_TbTaiKhoanKh_TenTaiKhoan");

                    b.ToTable("TbTaiKhoanKhs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTinTuc", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTinTuc"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaTinTuc");

                    b.ToTable("TbTinTucs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbChiTietHoaDonBan", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbHoaDonBan", "MaHoaDonNavigation")
                        .WithMany("TbChiTietHoaDonBans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbSanPham", "MaSanPhamNavigation")
                        .WithMany("TbChiTietHoaDonBans")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbGioHang", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbKhachHang", "MaKhachHangNavigation")
                        .WithMany("TbGioHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbSanPham", "MaSanPhamNavigation")
                        .WithMany("TbGioHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbHoaDonBan", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbKhachHang", "MaKhachHangNavigation")
                        .WithMany("TbHoaDonBans")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbNhanVien", "MaNhanVienNavigation")
                        .WithMany("TbHoaDonBans")
                        .HasForeignKey("MaNhanVien");

                    b.HasOne("CoffeeHouse.Models.TbQuanCafe", "MaQuanNavigation")
                        .WithMany("TbHoaDonBans")
                        .HasForeignKey("MaQuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaQuanNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhanVien", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbQuanCafe", "MaQuanNavigation")
                        .WithMany("TbNhanViens")
                        .HasForeignKey("MaQuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaQuanNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapChiTiet", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbNguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("TbPhieuNhapChiTiets")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbPhieuNhapHang", "MaPhieuNhapNavigation")
                        .WithMany("TbPhieuNhapChiTiets")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNguyenLieuNavigation");

                    b.Navigation("MaPhieuNhapNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapHang", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbNhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("TbPhieuNhapHangs")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbNhanVien", "MaNhanVienNavigation")
                        .WithMany("TbPhieuNhapHangs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbQuanCafe", "MaQuanNavigation")
                        .WithMany("TbPhieuNhapHangs")
                        .HasForeignKey("MaQuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNhaCungCapNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaQuanNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbSanPham", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbNhomSanPham", "MaNhomSpNavigation")
                        .WithMany("TbSanPhams")
                        .HasForeignKey("MaNhomSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNhomSpNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTaiKhoan", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbNhanVien", "MaNhanVienNavigation")
                        .WithMany("TbTaiKhoans")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbQuyen", "MaQuyenNavigation")
                        .WithMany("TbTaiKhoans")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbTaiKhoanKh", b =>
                {
                    b.HasOne("CoffeeHouse.Models.TbKhachHang", "MaKhachHangNavigation")
                        .WithMany("TbTaiKhoanKhs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHouse.Models.TbQuyen", "MaQuyenNavigation")
                        .WithMany("TbTaiKhoanKhs")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbHoaDonBan", b =>
                {
                    b.Navigation("TbChiTietHoaDonBans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbKhachHang", b =>
                {
                    b.Navigation("TbGioHangs");

                    b.Navigation("TbHoaDonBans");

                    b.Navigation("TbTaiKhoanKhs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNguyenLieu", b =>
                {
                    b.Navigation("TbPhieuNhapChiTiets");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhaCungCap", b =>
                {
                    b.Navigation("TbPhieuNhapHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhanVien", b =>
                {
                    b.Navigation("TbHoaDonBans");

                    b.Navigation("TbPhieuNhapHangs");

                    b.Navigation("TbTaiKhoans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbNhomSanPham", b =>
                {
                    b.Navigation("TbSanPhams");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbPhieuNhapHang", b =>
                {
                    b.Navigation("TbPhieuNhapChiTiets");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuanCafe", b =>
                {
                    b.Navigation("TbHoaDonBans");

                    b.Navigation("TbNhanViens");

                    b.Navigation("TbPhieuNhapHangs");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbQuyen", b =>
                {
                    b.Navigation("TbTaiKhoanKhs");

                    b.Navigation("TbTaiKhoans");
                });

            modelBuilder.Entity("CoffeeHouse.Models.TbSanPham", b =>
                {
                    b.Navigation("TbChiTietHoaDonBans");

                    b.Navigation("TbGioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
